include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippets:
     - cdc-acm-console
     - studio-rpc-usb-uart
     - zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
